dependencies:
- decorator
- ipython
- ipython_genutils
- openssl
- path.py
- pexpect
- pickleshare
- pip
- prompt_toolkit
- ptyprocess
- pygments
- python
- readline
- setuptools
- simplegeneric
- six
- sqlite
- tk
- traitlets
- wcwidth
- wheel
- xz
- zlib
- pip:
  - alabaster
  - babel
  - breathe
  - docutils
  - entrypoints
  - imagesize
  - ipython-genutils
  - jinja2
  - jsonschema
  - jupyter-core
  - markupsafe
  - mistune
  - nbconvert
  - nbformat
  - nbsphinx
  - prompt-toolkit
  - pytz
  - snowballstemmer
